// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackLab.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace Alumware.Tracklab.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250615225731_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_employees");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_positions");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string>("ImageAssetIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_asset_ids");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("license_plate");

                    b.Property<decimal>("LoadCapacity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("load_capacity");

                    b.Property<int>("PaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("pax_capacity");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_vehicles");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_warehouses");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Employee", b =>
                {
                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_employees_employees_employee_id");
                        });

                    b.OwnsOne("Alumware.Tracklab.API.Resource.Domain.Model.ValueObjects.Dni", "Dni", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("dni");

                            b1.HasKey("Id");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_employees_employees_employee_id");
                        });

                    b.OwnsOne("Alumware.Tracklab.API.Resource.Domain.Model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("Id");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_employees_employees_employee_id");
                        });

                    b.Navigation("Dni")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Position", b =>
                {
                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("positions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_positions_positions_position_id");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.OwnsOne("Alumware.Tracklab.API.Resource.Domain.Model.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("location_longitude");

                            b1.HasKey("Id");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_vehicle_id");
                        });

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_vehicle_id");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Warehouse", b =>
                {
                    b.OwnsOne("Alumware.Tracklab.API.Resource.Domain.Model.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("longitude");

                            b1.HasKey("Id");

                            b1.ToTable("warehouses");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_warehouses_warehouses_warehouse_id");
                        });

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("warehouses");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_warehouses_warehouses_warehouse_id");
                        });

                    b.OwnsOne("Alumware.Tracklab.API.Resource.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address");

                            b1.HasKey("Id");

                            b1.ToTable("warehouses");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_warehouses_warehouses_warehouse_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
