// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackLab.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace Alumware.Tracklab.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619043807_AddTrackingContext")]
    partial class AddTrackingContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Alumware.Tracklab.API.Order.Domain.Model.Aggregates.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shipping_address");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("OrderId")
                        .HasName("p_k_orders");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Order.Domain.Model.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("p_k_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("i_x_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_employees");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_positions");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string>("ImageAssetIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_asset_ids");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("license_plate");

                    b.Property<decimal>("LoadCapacity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("load_capacity");

                    b.Property<int>("PaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("pax_capacity");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_vehicles");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_warehouses");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Tracking.Domain.Model.Aggregates.Container", b =>
                {
                    b.Property<long>("ContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("container_id");

                    b.HasKey("ContainerId")
                        .HasName("p_k_containers");

                    b.ToTable("containers", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Tracking.Domain.Model.Aggregates.Route", b =>
                {
                    b.Property<long>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("route_id");

                    b.HasKey("RouteId")
                        .HasName("p_k_routes");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Tracking.Domain.Model.Aggregates.TrackingEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<long>("ContainerId")
                        .HasColumnType("bigint")
                        .HasColumnName("container_id");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_time");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.ToTable("tracking_events", (string)null);
                });

            modelBuilder.Entity("TrackLab.IAM.Domain.Model.Aggregates.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("CommercialName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("commercial_name");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("country");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("ruc");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("p_k_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("TrackLab.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RolesInternal")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("roles");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Order.Domain.Model.Aggregates.Order", b =>
                {
                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "LogisticsId", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint")
                                .HasColumnName("order_id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("logistics_id");

                            b1.HasKey("OrderId")
                                .HasName("p_k_orders");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("f_k_orders_orders_order_id");
                        });

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint")
                                .HasColumnName("order_id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("customer_id");

                            b1.HasKey("OrderId")
                                .HasName("p_k_orders");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("f_k_orders_orders_order_id");
                        });

                    b.Navigation("LogisticsId")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Order.Domain.Model.Entities.OrderItem", b =>
                {
                    b.HasOne("Alumware.Tracklab.API.Order.Domain.Model.Aggregates.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("f_k_order_items_orders_order_id");

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("price_currency");

                            b1.HasKey("Id");

                            b1.ToTable("order_items");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_order_items_order_items_order_item_id");
                        });

                    b.OwnsOne("Alumware.Tracklab.API.Order.Domain.Model.ValueObjects.ProductId", "ProductId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("product_id");

                            b1.HasKey("Id");

                            b1.ToTable("order_items");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_order_items_order_items_order_item_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("ProductId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Employee", b =>
                {
                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("Id");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_employees_employees_employee_id");
                        });

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_employees_employees_employee_id");
                        });

                    b.OwnsOne("Alumware.Tracklab.API.Resource.Domain.Model.ValueObjects.Dni", "Dni", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("dni");

                            b1.HasKey("Id");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_employees_employees_employee_id");
                        });

                    b.Navigation("Dni")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Position", b =>
                {
                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("positions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_positions_positions_position_id");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Product", b =>
                {
                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("price_currency");

                            b1.HasKey("Id");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_products_products_product_id");
                        });

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_products_products_product_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.OwnsOne("Alumware.Tracklab.API.Resource.Domain.Model.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("location_longitude");

                            b1.HasKey("Id");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_vehicle_id");
                        });

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_vehicle_id");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Resource.Domain.Model.Aggregates.Warehouse", b =>
                {
                    b.OwnsOne("Alumware.Tracklab.API.Resource.Domain.Model.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("longitude");

                            b1.HasKey("Id");

                            b1.ToTable("warehouses");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_warehouses_warehouses_warehouse_id");
                        });

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("warehouses");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_warehouses_warehouses_warehouse_id");
                        });

                    b.OwnsOne("Alumware.Tracklab.API.Resource.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address");

                            b1.HasKey("Id");

                            b1.ToTable("warehouses");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_warehouses_warehouses_warehouse_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Tracking.Domain.Model.Aggregates.Container", b =>
                {
                    b.OwnsOne("Alumware.Tracklab.API.Tracking.Domain.Model.ValueObjects.OrderId", "OrderId", b1 =>
                        {
                            b1.Property<long>("ContainerId")
                                .HasColumnType("bigint")
                                .HasColumnName("container_id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("order_id");

                            b1.HasKey("ContainerId")
                                .HasName("p_k_containers");

                            b1.ToTable("containers");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId")
                                .HasConstraintName("f_k_containers_containers_container_id");
                        });

                    b.OwnsOne("Alumware.Tracklab.API.Tracking.Domain.Model.ValueObjects.WarehouseId", "WarehouseId", b1 =>
                        {
                            b1.Property<long>("ContainerId")
                                .HasColumnType("bigint")
                                .HasColumnName("container_id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("warehouse_id");

                            b1.HasKey("ContainerId")
                                .HasName("p_k_containers");

                            b1.ToTable("containers");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId")
                                .HasConstraintName("f_k_containers_containers_container_id");
                        });

                    b.OwnsMany("Alumware.Tracklab.API.Tracking.Domain.Model.ValueObjects.ShipItem", "ShipItems", b1 =>
                        {
                            b1.Property<long>("ContainerId")
                                .HasColumnType("bigint");

                            b1.Property<long>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("product_id");

                            b1.Property<long>("Quantity")
                                .HasColumnType("bigint")
                                .HasColumnName("quantity");

                            b1.HasKey("ContainerId", "ProductId");

                            b1.ToTable("ship_items");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId")
                                .HasConstraintName("f_k_ship_items_containers_container_id");
                        });

                    b.Navigation("OrderId")
                        .IsRequired();

                    b.Navigation("ShipItems");

                    b.Navigation("WarehouseId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Tracking.Domain.Model.Aggregates.Route", b =>
                {
                    b.OwnsMany("Alumware.Tracklab.API.Tracking.Domain.Model.ValueObjects.OrderId", "Orders", b1 =>
                        {
                            b1.Property<long>("RouteId")
                                .HasColumnType("bigint")
                                .HasColumnName("route_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("order_id");

                            b1.HasKey("RouteId", "Id")
                                .HasName("p_k_routes__orders");

                            b1.ToTable("routes__orders");

                            b1.WithOwner()
                                .HasForeignKey("RouteId")
                                .HasConstraintName("f_k_routes__orders_routes_route_id");
                        });

                    b.OwnsMany("Alumware.Tracklab.API.Tracking.Domain.Model.Entities.RouteItem", "RouteItems", b1 =>
                        {
                            b1.Property<long>("RouteId")
                                .HasColumnType("bigint");

                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("completed_at");

                            b1.Property<bool>("IsCompleted")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("is_completed");

                            b1.Property<long>("WarehouseId")
                                .HasColumnType("bigint")
                                .HasColumnName("warehouse_id");

                            b1.HasKey("RouteId", "Id");

                            b1.ToTable("route_items");

                            b1.WithOwner()
                                .HasForeignKey("RouteId")
                                .HasConstraintName("f_k_route_items_routes_route_id");
                        });

                    b.OwnsOne("Alumware.Tracklab.API.Tracking.Domain.Model.ValueObjects.VehicleId", "VehicleId", b1 =>
                        {
                            b1.Property<long>("RouteId")
                                .HasColumnType("bigint")
                                .HasColumnName("route_id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("vehicle_id");

                            b1.HasKey("RouteId")
                                .HasName("p_k_routes");

                            b1.ToTable("routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId")
                                .HasConstraintName("f_k_routes_routes_route_id");
                        });

                    b.Navigation("Orders");

                    b.Navigation("RouteItems");

                    b.Navigation("VehicleId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Tracking.Domain.Model.Aggregates.TrackingEvent", b =>
                {
                    b.OwnsOne("Alumware.Tracklab.API.Tracking.Domain.Model.ValueObjects.WarehouseId", "WarehouseId", b1 =>
                        {
                            b1.Property<long>("EventId")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("warehouse_id");

                            b1.HasKey("EventId");

                            b1.ToTable("tracking_events");

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("f_k_tracking_events_tracking_events_tracking_event_temp_id");
                        });

                    b.Navigation("WarehouseId")
                        .IsRequired();
                });

            modelBuilder.Entity("TrackLab.IAM.Domain.Model.Aggregates.Tenant", b =>
                {
                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("Id");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_tenants_tenants_tenant_id");
                        });

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("phone_number");

                            b1.HasKey("Id");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_tenants_tenants_tenant_id");
                        });

                    b.Navigation("Email");

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("TrackLab.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("Id");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_user_id");
                        });

                    b.OwnsOne("TrackLab.Shared.Domain.ValueObjects.TenantId", "TenantId", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_user_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Alumware.Tracklab.API.Order.Domain.Model.Aggregates.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
